# Generated by Django 2.2.5 on 2019-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_Vision_IMSsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='Vision_IMSsetting',
            name='description',
            field=models.CharField(blank=True, help_text='Settings description', max_length=200),
        ),
        migrations.AlterField(
            model_name='Vision_IMSsetting',
            name='key',
            field=models.CharField(help_text='Settings key (must be unique - case insensitive', max_length=50, unique=True),
        ),
    ]
