# Generated by Django 2.2.9 on 2020-02-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190915_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Vision_IMSsetting',
            options={'verbose_name': 'Vision_IMS Setting', 'verbose_name_plural': 'Vision_IMS Settings'},
        ),
    ]
